//! YAML-object normalization shared by editor fetch, validation, and apply operations.

use anyhow::{Context, Result};
use kube::api::DynamicObject;

const SERVER_MANAGED_METADATA_FIELDS: [&str; 4] = [
    "managedFields",
    "resourceVersion",
    "uid",
    "creationTimestamp",
];

pub(super) enum ReplacementPreparation {
    Ready(Box<DynamicObject>),
    Conflict,
}

/// Remove fields which are generated by the API server and must not be sent back as part of an
/// editor payload. Clear both the dynamic JSON representation and kube's typed metadata because
/// serialization can read either one.
pub(super) fn strip_server_managed_metadata(object: &mut DynamicObject) {
    if let Some(metadata) = object.data.get_mut("metadata")
        && let Some(metadata) = metadata.as_object_mut()
    {
        for field in SERVER_MANAGED_METADATA_FIELDS {
            metadata.remove(field);
        }
    }
    object.metadata.managed_fields = None;
    object.metadata.resource_version = None;
    object.metadata.uid = None;
    object.metadata.creation_timestamp = None;
}

/// Convert an API response to the YAML shown by the editor while retaining the
/// version needed to safely replace that exact resource later.
pub(super) fn editor_yaml(object: &mut DynamicObject) -> Result<(String, String, String)> {
    let resource_version = resource_version(object)?;
    let resource_uid = resource_uid(object)?;
    strip_server_managed_metadata(object);
    Ok((
        serde_yaml::to_string(object)?,
        resource_version,
        resource_uid,
    ))
}

pub(super) fn resource_version(object: &DynamicObject) -> Result<String> {
    object
        .metadata
        .resource_version
        .clone()
        .context("Resource response did not include a resource version")
}

pub(super) fn resource_uid(object: &DynamicObject) -> Result<String> {
    object
        .metadata
        .uid
        .clone()
        .context("Resource response did not include a UID")
}

/// Normalize an edited object for a full replacement request. The editor does
/// not expose server-managed metadata, but replacement requires the version
/// that was fetched with the editor document.
pub(super) fn prepare_resource_replacement(object: &mut DynamicObject, resource_version: String) {
    strip_server_managed_metadata(object);
    object.metadata.resource_version = Some(resource_version);
}

/// Prepare editor content for a full replacement against the current object.
/// Status-only reconciliation may advance the resource version without
/// changing editable content; any other live change is a conflict. The current
/// status is always retained because controllers own it independently.
pub(super) fn prepare_editor_replacement(
    original_yaml: &str,
    edited_yaml: &str,
    expected_resource_version: &str,
    expected_resource_uid: &str,
    current: &mut DynamicObject,
) -> Result<ReplacementPreparation> {
    let current_resource_version = resource_version(current)?;
    if resource_uid(current)? != expected_resource_uid
        || (current_resource_version != expected_resource_version
            && has_non_status_changes(original_yaml, current)?)
    {
        return Ok(ReplacementPreparation::Conflict);
    }

    let mut edited: DynamicObject = serde_yaml::from_str(edited_yaml)?;
    retain_current_status(&mut edited, current);
    prepare_resource_replacement(&mut edited, current_resource_version);
    Ok(ReplacementPreparation::Ready(Box::new(edited)))
}

fn retain_current_status(edited: &mut DynamicObject, current: &DynamicObject) {
    let Some(edited_data) = edited.data.as_object_mut() else {
        return;
    };
    match current.data.get("status") {
        Some(status) => {
            edited_data.insert("status".into(), status.clone());
        }
        None => {
            edited_data.remove("status");
        }
    }
}

/// Return whether an object has changed in a way that a full replacement must
/// not overwrite. Resource status is reconciled independently by controllers,
/// so a status-only update is safe to retry with the current resource version.
pub(super) fn has_non_status_changes(
    original_yaml: &str,
    current: &mut DynamicObject,
) -> Result<bool> {
    let mut original: DynamicObject = serde_yaml::from_str(original_yaml)?;
    Ok(editable_value(&mut original)? != editable_value(current)?)
}

fn editable_value(object: &mut DynamicObject) -> Result<k8s_openapi::serde_json::Value> {
    strip_server_managed_metadata(object);
    let mut value = k8s_openapi::serde_json::to_value(object)?;
    if let Some(value) = value.as_object_mut() {
        value.remove("status");
    }
    Ok(value)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_server_managed_fields_from_both_metadata_representations() {
        let mut object: DynamicObject =
            k8s_openapi::serde_json::from_value(k8s_openapi::serde_json::json!({
                "apiVersion": "v1",
                "kind": "ConfigMap",
                "metadata": {
                    "name": "settings",
                    "managedFields": [{}],
                    "resourceVersion": "4",
                    "uid": "uid-1",
                    "creationTimestamp": "2026-01-01T00:00:00Z"
                }
            }))
            .unwrap();
        // Dynamic objects received through kube retain this map, while direct serde
        // deserialization normalizes it into `ObjectMeta`. Exercise both paths.
        object.data.as_object_mut().unwrap().insert(
            "metadata".to_owned(),
            k8s_openapi::serde_json::json!({
                "name": "settings",
                "managedFields": [{}],
                "resourceVersion": "4",
                "uid": "uid-1",
                "creationTimestamp": "2026-01-01T00:00:00Z"
            }),
        );

        strip_server_managed_metadata(&mut object);

        let metadata = object.data["metadata"].as_object().unwrap();
        assert_eq!(metadata.get("name").unwrap(), "settings");
        for field in SERVER_MANAGED_METADATA_FIELDS {
            assert!(!metadata.contains_key(field));
        }
        assert!(object.metadata.managed_fields.is_none());
        assert!(object.metadata.resource_version.is_none());
        assert!(object.metadata.uid.is_none());
        assert!(object.metadata.creation_timestamp.is_none());
        let yaml = serde_yaml::to_string(&object).unwrap();
        assert!(yaml.contains("name: settings"));
        for field in SERVER_MANAGED_METADATA_FIELDS {
            assert!(!yaml.contains(field));
        }
    }

    #[test]
    fn editor_yaml_hides_the_resource_version_but_returns_it_for_replacement() {
        let mut object: DynamicObject =
            k8s_openapi::serde_json::from_value(k8s_openapi::serde_json::json!({
                "apiVersion": "v1",
                "kind": "ConfigMap",
                "metadata": {
                    "name": "settings",
                    "resourceVersion": "42",
                    "uid": "uid-1"
                }
            }))
            .unwrap();

        let (yaml, resource_version, resource_uid) = editor_yaml(&mut object).unwrap();

        assert_eq!(resource_version, "42");
        assert_eq!(resource_uid, "uid-1");
        assert!(!yaml.contains("resourceVersion"));
    }

    #[test]
    fn replacement_restores_only_the_resource_version() {
        let mut object: DynamicObject =
            k8s_openapi::serde_json::from_value(k8s_openapi::serde_json::json!({
                "apiVersion": "v1",
                "kind": "ConfigMap",
                "metadata": {
                    "name": "settings",
                    "uid": "uid-1",
                    "managedFields": [{}]
                }
            }))
            .unwrap();

        prepare_resource_replacement(&mut object, "42".into());

        let value = k8s_openapi::serde_json::to_value(object).unwrap();
        let metadata = value["metadata"].as_object().unwrap();
        assert_eq!(metadata.get("resourceVersion").unwrap(), "42");
        assert!(!metadata.contains_key("uid"));
        assert!(!metadata.contains_key("managedFields"));
    }

    #[test]
    fn status_only_changes_do_not_conflict_with_a_replacement() {
        let original_yaml = r#"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
"#;
        let mut current: DynamicObject =
            k8s_openapi::serde_json::from_value(k8s_openapi::serde_json::json!({
                "apiVersion": "apps/v1",
                "kind": "Deployment",
                "metadata": {
                    "name": "api",
                    "resourceVersion": "2",
                    "uid": "uid-1"
                },
                "spec": {
                    "replicas": 1
                },
                "status": {
                    "availableReplicas": 1
                }
            }))
            .unwrap();

        assert!(!has_non_status_changes(original_yaml, &mut current).unwrap());
    }

    #[test]
    fn editable_changes_conflict_with_a_replacement() {
        let original_yaml = r#"
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
data:
  mode: production
"#;
        let mut current: DynamicObject =
            k8s_openapi::serde_json::from_value(k8s_openapi::serde_json::json!({
                "apiVersion": "v1",
                "kind": "ConfigMap",
                "metadata": {
                    "name": "settings",
                    "resourceVersion": "2",
                    "uid": "uid-1"
                },
                "data": {
                    "mode": "maintenance"
                }
            }))
            .unwrap();

        assert!(has_non_status_changes(original_yaml, &mut current).unwrap());
    }

    #[test]
    fn replacement_preparation_rebases_a_status_only_update() {
        let original_yaml = "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: settings\ndata:\n  mode: production\n";
        let edited_yaml = "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: settings\ndata:\n  mode: maintenance\n";
        let mut current: DynamicObject =
            k8s_openapi::serde_json::from_value(k8s_openapi::serde_json::json!({
                "apiVersion": "v1",
                "kind": "ConfigMap",
                "metadata": {
                    "name": "settings",
                    "resourceVersion": "2",
                    "uid": "uid-1"
                },
                "data": {
                    "mode": "production"
                },
                "status": {
                    "ignored": true
                }
            }))
            .unwrap();

        let ReplacementPreparation::Ready(prepared) =
            prepare_editor_replacement(original_yaml, edited_yaml, "1", "uid-1", &mut current)
                .unwrap()
        else {
            panic!("status-only updates should not conflict");
        };

        assert_eq!(prepared.metadata.resource_version.as_deref(), Some("2"));
        assert_eq!(prepared.data["data"]["mode"], "maintenance");
        assert_eq!(prepared.data["status"]["ignored"], true);
    }

    #[test]
    fn replacement_preparation_preserves_live_status_over_editor_status() {
        let yaml = "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: settings\nstatus:\n  mode: stale\n";
        let mut current: DynamicObject =
            k8s_openapi::serde_json::from_value(k8s_openapi::serde_json::json!({
                "apiVersion": "v1",
                "kind": "ConfigMap",
                "metadata": {
                    "name": "settings",
                    "resourceVersion": "1",
                    "uid": "uid-1"
                },
                "status": {
                    "mode": "live"
                }
            }))
            .unwrap();

        let ReplacementPreparation::Ready(prepared) =
            prepare_editor_replacement(yaml, yaml, "1", "uid-1", &mut current).unwrap()
        else {
            panic!("an unchanged object should prepare for replacement");
        };

        assert_eq!(prepared.data["status"]["mode"], "live");
    }

    #[test]
    fn replacement_preparation_conflicts_when_the_resource_was_recreated() {
        let yaml = "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: settings\n";
        let mut current: DynamicObject =
            k8s_openapi::serde_json::from_value(k8s_openapi::serde_json::json!({
                "apiVersion": "v1",
                "kind": "ConfigMap",
                "metadata": {
                    "name": "settings",
                    "resourceVersion": "2",
                    "uid": "new-uid"
                }
            }))
            .unwrap();

        assert!(matches!(
            prepare_editor_replacement(yaml, yaml, "1", "old-uid", &mut current).unwrap(),
            ReplacementPreparation::Conflict
        ));
    }
}
