//! YAML-object normalization shared by editor fetch, validation, and apply operations.

use kube::api::DynamicObject;

const SERVER_MANAGED_METADATA_FIELDS: [&str; 4] = [
    "managedFields",
    "resourceVersion",
    "uid",
    "creationTimestamp",
];

/// Remove fields which are generated by the API server and must not be sent back as part of an
/// editor payload. Clear both the dynamic JSON representation and kube's typed metadata because
/// serialization can read either one.
pub(super) fn strip_server_managed_metadata(object: &mut DynamicObject) {
    if let Some(metadata) = object.data.get_mut("metadata")
        && let Some(metadata) = metadata.as_object_mut()
    {
        for field in SERVER_MANAGED_METADATA_FIELDS {
            metadata.remove(field);
        }
    }
    object.metadata.managed_fields = None;
    object.metadata.resource_version = None;
    object.metadata.uid = None;
    object.metadata.creation_timestamp = None;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_server_managed_fields_from_both_metadata_representations() {
        let mut object: DynamicObject =
            k8s_openapi::serde_json::from_value(k8s_openapi::serde_json::json!({
                "apiVersion": "v1",
                "kind": "ConfigMap",
                "metadata": {
                    "name": "settings",
                    "managedFields": [{}],
                    "resourceVersion": "4",
                    "uid": "uid-1",
                    "creationTimestamp": "2026-01-01T00:00:00Z"
                }
            }))
            .unwrap();
        // Dynamic objects received through kube retain this map, while direct serde
        // deserialization normalizes it into `ObjectMeta`. Exercise both paths.
        object.data.as_object_mut().unwrap().insert(
            "metadata".to_owned(),
            k8s_openapi::serde_json::json!({
                "name": "settings",
                "managedFields": [{}],
                "resourceVersion": "4",
                "uid": "uid-1",
                "creationTimestamp": "2026-01-01T00:00:00Z"
            }),
        );

        strip_server_managed_metadata(&mut object);

        let metadata = object.data["metadata"].as_object().unwrap();
        assert_eq!(metadata.get("name").unwrap(), "settings");
        for field in SERVER_MANAGED_METADATA_FIELDS {
            assert!(!metadata.contains_key(field));
        }
        assert!(object.metadata.managed_fields.is_none());
        assert!(object.metadata.resource_version.is_none());
        assert!(object.metadata.uid.is_none());
        assert!(object.metadata.creation_timestamp.is_none());
        let yaml = serde_yaml::to_string(&object).unwrap();
        assert!(yaml.contains("name: settings"));
        for field in SERVER_MANAGED_METADATA_FIELDS {
            assert!(!yaml.contains(field));
        }
    }
}
