// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Styrhous.Licensing.Persistence;

#nullable disable

namespace Styrhous.Licensing.Persistence.Migrations
{
    [DbContext(typeof(LicensingDbContext))]
    partial class LicensingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01999999-0000-7000-8000-000000000001"),
                            ApplicationType = "native",
                            ClientId = "styrhous-desktop",
                            ClientType = "public",
                            ConcurrencyToken = "01999999-0000-7000-8000-000000000002",
                            ConsentType = "implicit",
                            DisplayName = "Styrhous desktop"
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Accounts.BillingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("PersonalOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_billing_accounts");

                    b.HasIndex("PersonalOwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_accounts_personal_owner_user_id")
                        .HasFilter("kind = 'Personal'");

                    b.ToTable("billing_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_billing_accounts_personal_owner", "(kind = 'Personal' AND personal_owner_user_id IS NOT NULL) OR (kind = 'Organization' AND personal_owner_user_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Accounts.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("device_limit");

                    b.Property<bool>("ProductAccessEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("product_access_enabled");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasAlternateKey("Id", "AssignedUserId")
                        .HasName("ak_seats_id_assigned_user_id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("BillingAccountId", "AssignedUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_seats_billing_account_user");

                    b.HasIndex("BillingAccountId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_seats_billing_account_created_id");

                    b.ToTable("seats", null, t =>
                        {
                            t.HasCheckConstraint("ck_seats_device_limit", "device_limit > 0");
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Auditing.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_records");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_records_correlation_id");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_records_target");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Billing.BillingOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<string>("Cadence")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cadence");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_session_id");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_subscription_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<int?>("PreviousSeatQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("previous_seat_quantity");

                    b.Property<string>("PreviousSubscription")
                        .HasColumnType("jsonb")
                        .HasColumnName("previous_subscription");

                    b.Property<DateTimeOffset?>("ProviderMutationReplayStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provider_mutation_replay_started_at");

                    b.Property<DateTimeOffset?>("ProviderSessionRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provider_session_recorded_at");

                    b.Property<int>("SeatQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("seat_quantity");

                    b.Property<string>("SeatQuantityOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("seat_quantity_outcome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_billing_operations");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("BillingAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_operations_live_account")
                        .HasFilter("status IN ('Pending', 'ProviderSessionCreated')");

                    b.HasIndex("ExternalSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_operations_external_session_id")
                        .HasFilter("external_session_id IS NOT NULL");

                    b.HasIndex("BillingAccountId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_billing_operations_account_created_id");

                    b.ToTable("billing_operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_billing_operations_cadence", "(kind = 'InitialCheckout' AND cadence IN ('Monthly', 'Annual') AND previous_seat_quantity IS NULL) OR (kind = 'SeatQuantityChange' AND cadence IS NULL AND previous_seat_quantity IS NOT NULL AND previous_seat_quantity <> seat_quantity)");

                            t.HasCheckConstraint("ck_billing_operations_kind", "kind IN ('InitialCheckout', 'SeatQuantityChange')");

                            t.HasCheckConstraint("ck_billing_operations_lifecycle", "(kind = 'InitialCheckout' AND expires_at IS NOT NULL AND provider_mutation_replay_started_at IS NULL AND seat_quantity_outcome IS NULL AND ((status = 'Pending' AND provider_session_recorded_at IS NULL AND external_session_id IS NULL AND closed_at IS NULL) OR (status = 'ProviderSessionCreated' AND provider_session_recorded_at IS NOT NULL AND external_session_id IS NOT NULL AND closed_at IS NULL) OR (status = 'Completed' AND closed_at IS NOT NULL AND ((provider_session_recorded_at IS NOT NULL AND external_session_id IS NOT NULL) OR (provider_session_recorded_at IS NULL AND external_session_id IS NULL AND external_subscription_id IS NOT NULL))) OR (status = 'Failed' AND provider_session_recorded_at IS NULL AND external_session_id IS NULL AND closed_at IS NOT NULL) OR (status = 'Expired' AND provider_session_recorded_at IS NOT NULL AND external_session_id IS NOT NULL AND closed_at IS NOT NULL))) OR (kind = 'SeatQuantityChange' AND expires_at IS NULL AND provider_session_recorded_at IS NULL AND external_session_id IS NULL AND ((status = 'Pending' AND closed_at IS NULL AND seat_quantity_outcome IS NULL) OR (status = 'Completed' AND closed_at IS NOT NULL AND seat_quantity_outcome = 'Applied') OR (status = 'Failed' AND closed_at IS NOT NULL AND seat_quantity_outcome IN ('Superseded', 'ProviderRejected'))))");

                            t.HasCheckConstraint("ck_billing_operations_seat_quantity", "seat_quantity > 0 AND (previous_seat_quantity IS NULL OR previous_seat_quantity > 0)");

                            t.HasCheckConstraint("ck_billing_operations_status", "status IN ('Pending', 'ProviderSessionCreated', 'Completed', 'Failed', 'Expired')");

                            t.HasCheckConstraint("ck_billing_operations_valid_window", "(expires_at IS NULL OR expires_at > created_at) AND (provider_session_recorded_at IS NULL OR provider_session_recorded_at >= created_at) AND (closed_at IS NULL OR closed_at >= created_at)");
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Billing.BillingWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_event_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<bool>("NativeOutboxEnqueued")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempt_count");

                    b.Property<DateTimeOffset?>("ProcessingLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_lease_expires_at");

                    b.Property<Guid?>("ProcessingLeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_lease_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_billing_webhook_events");

                    b.HasIndex("ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_webhook_events_external_event_id");

                    b.HasIndex("ReceivedAt", "Id")
                        .HasDatabaseName("ix_billing_webhook_events_pending_received_id")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("billing_webhook_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_billing_webhook_events_kind", "kind IN ('CheckoutCompleted', 'SubscriptionChanged', 'InvoicePaid', 'PaymentFailed', 'Unsupported')");

                            t.HasCheckConstraint("ck_billing_webhook_events_processing_attempts", "processing_attempt_count >= 0");

                            t.HasCheckConstraint("ck_billing_webhook_events_processing_lease", "(processing_lease_id IS NULL) = (processing_lease_expires_at IS NULL)");

                            t.HasCheckConstraint("ck_billing_webhook_events_processing_state", "processed_at IS NULL OR processing_lease_id IS NULL");
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Billing.CommercialSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset>("CurrentPeriodEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_ends_at");

                    b.Property<DateTimeOffset>("CurrentPeriodStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_started_at");

                    b.Property<string>("ExternalCustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_customer_id");

                    b.Property<string>("ExternalPriceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_price_id");

                    b.Property<string>("ExternalSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_subscription_id");

                    b.Property<DateTimeOffset>("ProjectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projected_at");

                    b.Property<long>("ProviderReadRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_read_revision");

                    b.Property<string>("ProviderSnapshotKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider_snapshot_kind");

                    b.Property<int>("SeatQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("seat_quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_commercial_subscriptions");

                    b.HasIndex("BillingAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_commercial_subscriptions_billing_account_id");

                    b.HasIndex("ExternalCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_commercial_subscriptions_external_customer_id");

                    b.HasIndex("ExternalSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_commercial_subscriptions_external_subscription_id");

                    b.ToTable("commercial_subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_commercial_subscriptions_provider_read_revision", "provider_read_revision >= 0");

                            t.HasCheckConstraint("ck_commercial_subscriptions_provider_snapshot_kind", "provider_snapshot_kind IN ('Observation', 'MutationResponse')");

                            t.HasCheckConstraint("ck_commercial_subscriptions_seat_quantity", "seat_quantity > 0");

                            t.HasCheckConstraint("ck_commercial_subscriptions_status", "status IN ('Active', 'PastDue', 'Unpaid', 'Paused', 'Incomplete', 'IncompleteExpired', 'Trialing', 'Canceled')");

                            t.HasCheckConstraint("ck_commercial_subscriptions_valid_period", "current_period_ends_at > current_period_started_at");
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Devices.DesktopDeviceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivationId")
                        .HasColumnType("uuid")
                        .HasColumnName("activation_id");

                    b.Property<Guid>("AuthorizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorization_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_desktop_device_sessions");

                    b.HasIndex("ActivationId")
                        .HasDatabaseName("ix_desktop_device_sessions_activation_id");

                    b.HasIndex("AuthorizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_desktop_device_sessions_authorization_id");

                    b.ToTable("desktop_device_sessions", (string)null);
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Devices.DeviceActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("architecture");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("platform");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<string>("StyrhousVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("styrhous_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_activations");

                    b.HasIndex("SeatId", "InstallationId")
                        .IsUnique()
                        .HasDatabaseName("ux_device_activations_active_seat_installation")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("SeatId", "LastSeenAt")
                        .HasDatabaseName("ix_device_activations_active_last_seen")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("SeatId", "UserId");

                    b.ToTable("device_activations", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_activations_timestamps", "last_seen_at >= activated_at AND ((revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL AND revoked_at >= last_seen_at))");
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DiscardReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("discard_reason");

                    b.Property<DateTimeOffset?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discarded_at");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_type");

                    b.Property<bool>("NativeOutboxEnqueued")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("ProcessingAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempt_count");

                    b.Property<DateTimeOffset?>("ProcessingLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_lease_expires_at");

                    b.Property<Guid?>("ProcessingLeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_lease_id");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("protected_payload");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_messages_correlation_id");

                    b.HasIndex("SubjectId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_outbox_messages_pending_subject_occurred_id")
                        .HasFilter("delivered_at IS NULL AND discarded_at IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_lifecycle", "(not_after IS NULL OR not_after > occurred_at) AND (delivered_at IS NULL OR delivered_at >= occurred_at) AND ((discarded_at IS NULL AND discard_reason IS NULL) OR (discarded_at IS NOT NULL AND discard_reason IS NOT NULL AND discarded_at >= occurred_at)) AND NOT (delivered_at IS NOT NULL AND discarded_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_outbox_messages_processing_attempts", "processing_attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_messages_processing_lease", "(processing_lease_id IS NULL) = (processing_lease_expires_at IS NULL) AND (processing_lease_expires_at IS NULL OR processing_lease_expires_at > occurred_at)");

                            t.HasCheckConstraint("ck_outbox_messages_processing_state", "(delivered_at IS NULL AND discarded_at IS NULL) OR processing_lease_id IS NULL");
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("BillingAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_billing_account_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_organizations_created_by_user_id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Organizations.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<bool>("AssignProductSeat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("assign_product_seat");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("ReservedSeatCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_seat_capacity");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_organization_invitations");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_invitations_secret_hash");

                    b.HasIndex("OrganizationId", "ExpiresAt")
                        .HasDatabaseName("ix_organization_invitations_pending_expiry")
                        .HasFilter("accepted_at IS NULL AND cancelled_at IS NULL");

                    b.HasIndex("OrganizationId", "NormalizedEmail", "ExpiresAt")
                        .HasDatabaseName("ix_organization_invitations_pending_email")
                        .HasFilter("accepted_at IS NULL AND cancelled_at IS NULL");

                    b.ToTable("organization_invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organization_invitations_reserved_seat_capacity", "(assign_product_seat AND reserved_seat_capacity > 0) OR (NOT assign_product_seat AND reserved_seat_capacity = 0)");

                            t.HasCheckConstraint("ck_organization_invitations_terminal_state", "((accepted_at IS NULL AND accepted_by_user_id IS NULL) OR (accepted_at IS NOT NULL AND accepted_by_user_id IS NOT NULL)) AND NOT (accepted_at IS NOT NULL AND cancelled_at IS NOT NULL) AND (accepted_at IS NULL OR (accepted_at >= last_sent_at AND accepted_at < expires_at)) AND (cancelled_at IS NULL OR (cancelled_at >= last_sent_at AND cancelled_at < expires_at))");

                            t.HasCheckConstraint("ck_organization_invitations_valid_window", "last_sent_at >= created_at AND expires_at = last_sent_at + INTERVAL '168 hours'");
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_memberships");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_memberships_single_owner")
                        .HasFilter("role = 'Owner'");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_memberships_organization_user");

                    b.HasIndex("UserId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_organization_memberships_user_created_id");

                    b.ToTable("organization_memberships", (string)null);
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Signups.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_identities");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identities_provider_subject");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identities_user_provider");

                    b.ToTable("external_identities", (string)null);
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Signups.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("VerifiedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("verified_email");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Signups.VerifiedEmailClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_verified_email_claims");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_verified_email_claims_normalized_email");

                    b.HasIndex("UserId");

                    b.ToTable("verified_email_claims", (string)null);
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Trials.Trial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("OriginatingUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("originating_user_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminated_at");

                    b.Property<DateTimeOffset?>("TransferredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transferred_at");

                    b.HasKey("Id")
                        .HasName("pk_trials");

                    b.HasIndex("BillingAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_trials_billing_account_id");

                    b.HasIndex("OriginatingUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_trials_originating_user_id");

                    b.ToTable("trials", null, t =>
                        {
                            t.HasCheckConstraint("ck_trials_termination", "terminated_at IS NULL OR (terminated_at >= started_at AND terminated_at < ends_at)");

                            t.HasCheckConstraint("ck_trials_valid_window", "ends_at > started_at");
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Persistence.BillingProviderReadCursor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_billing_provider_read_cursors");

                    b.ToTable("billing_provider_read_cursors", null, t =>
                        {
                            t.HasCheckConstraint("ck_billing_provider_read_cursors_revision", "revision >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a05c8d-9f83-74b3-9197-d3087eab0559"),
                            Revision = 0L
                        });
                });

            modelBuilder.Entity("Styrhous.Licensing.Persistence.RebusOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Body")
                        .HasColumnType("bytea");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Sent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SourceQueue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("RebusOutbox", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken<System.Guid>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Accounts.BillingAccount", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("PersonalOwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_billing_accounts_personal_owner_user_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Accounts.Seat", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seats_assigned_user_id");

                    b.HasOne("Styrhous.Licensing.Domain.Accounts.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seats_billing_account_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Auditing.AuditRecord", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_records_actor_user_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Billing.BillingOperation", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_billing_operations_actor_user_id");

                    b.HasOne("Styrhous.Licensing.Domain.Accounts.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_billing_operations_billing_account_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Billing.CommercialSubscription", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Accounts.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commercial_subscriptions_billing_account_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Devices.DesktopDeviceSession", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Devices.DeviceActivation", null)
                        .WithMany()
                        .HasForeignKey("ActivationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_desktop_device_sessions_activation_id");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_desktop_device_sessions_authorization_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Devices.DeviceActivation", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Accounts.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId", "UserId")
                        .HasPrincipalKey("Id", "AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_activations_seat_user");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Organizations.Organization", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Accounts.BillingAccount", null)
                        .WithOne()
                        .HasForeignKey("Styrhous.Licensing.Domain.Organizations.Organization", "BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_billing_account_id");

                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_created_by_user_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Organizations.OrganizationInvitation", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organization_invitations_accepted_by_user_id");

                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_invitations_created_by_user_id");

                    b.HasOne("Styrhous.Licensing.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_invitations_organization_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organization_id");

                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_user_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Signups.ExternalIdentity", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_user_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Signups.VerifiedEmailClaim", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verified_email_claims_user_id");
                });

            modelBuilder.Entity("Styrhous.Licensing.Domain.Trials.Trial", b =>
                {
                    b.HasOne("Styrhous.Licensing.Domain.Accounts.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trials_billing_account_id");

                    b.HasOne("Styrhous.Licensing.Domain.Signups.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OriginatingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trials_originating_user_id");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
