[package]
name = "kubernetes-dev-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33"
egui = "0.33"
egui_extras = "0.33"
components = { path = "../components" }
kube = { version = "2.0", features = ["runtime"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1.48", features = ["rt-multi-thread", "full"] }
k8s-openapi = { version = "0.26", features = ["v1_31"] }
anyhow = "1.0"
futures-util = "0.3"
itertools = "0.14"

[dev-dependencies]
egui_kittest = { version = "0.33", features = ["eframe", "wgpu", "snapshot"] }
