mod ansi;
mod api_resource;
mod cluster_connection_manager;
mod helm_release;
mod helpers;
mod log_store;
mod minimal_namespace;
mod minimal_resource;
mod pod_metrics;
mod resource_catalog;
mod resource_detail;
mod resource_handlers;
mod resource_schema;
mod resource_table;
mod sorted_name;
mod terminal_launcher;
mod ui;
mod updater;
mod worker;

use ui::MyEguiApp;

#[doc(hidden)]
pub use ui::log_viewer_profile::LogViewerProfile;
#[cfg(any(test, feature = "benchmarks"))]
#[doc(hidden)]
pub use ui::yaml_editor_profile::YamlEditorProfile;

pub(crate) const DEFAULT_NATIVE_WINDOW_SIZE: [f32; 2] = [1200.0, 800.0];
pub(crate) const MIN_NATIVE_WINDOW_SIZE: [f32; 2] = [1000.0, 600.0];
#[cfg(target_os = "linux")]
const LINUX_DEVELOPMENT_DESKTOP_APP_ID: &str = "styrhous-dev";
#[cfg(target_os = "linux")]
const LINUX_PACKAGE_DESKTOP_APP_ID: &str = "styrhous";

fn native_app_icon() -> egui::IconData {
    eframe::icon_data::from_png_bytes(include_bytes!(
        "../../../assets/icons/kubernetes-dev-ui.png"
    ))
    .expect("the bundled application icon must be a valid PNG")
}

#[cfg(target_os = "linux")]
fn linux_desktop_app_id() -> &'static str {
    linux_desktop_app_id_for(
        cfg!(styrhous_release_build),
        std::env::var_os("APPIMAGE").is_some_and(|value| !value.is_empty()),
        std::env::current_exe().ok().as_deref(),
    )
}

#[cfg(target_os = "linux")]
fn linux_desktop_app_id_for(
    release_build: bool,
    is_appimage: bool,
    executable: Option<&std::path::Path>,
) -> &'static str {
    let is_system_package =
        executable.is_some_and(|path| path.starts_with("/usr") || path.starts_with("/nix/store"));

    if release_build || is_appimage || is_system_package {
        LINUX_PACKAGE_DESKTOP_APP_ID
    } else {
        LINUX_DEVELOPMENT_DESKTOP_APP_ID
    }
}

fn native_options() -> eframe::NativeOptions {
    let viewport = egui::ViewportBuilder::default()
        .with_inner_size(DEFAULT_NATIVE_WINDOW_SIZE)
        .with_min_inner_size(MIN_NATIVE_WINDOW_SIZE)
        .with_icon(native_app_icon());

    // Wayland compositors resolve taskbar icons through the application ID's
    // matching .desktop file. Packages use the `styrhous` ID generated by
    // cargo-packager; local builds use their own ID so the development entry
    // cannot shadow a package launcher.
    #[cfg(target_os = "linux")]
    let viewport = viewport.with_app_id(linux_desktop_app_id());

    eframe::NativeOptions {
        viewport,
        ..Default::default()
    }
}

pub fn run_native() {
    tracing_subscriber::fmt().init();
    updater::apply_staged_update();

    eframe::run_native(
        "Styrhous",
        native_options(),
        Box::new(|cc| Ok(Box::new(MyEguiApp::<worker::Worker>::new(cc)))),
    )
    .expect("eframe failed to start");
}

#[cfg(test)]
mod tests {
    #[cfg(target_os = "linux")]
    use super::linux_desktop_app_id_for;
    use super::{DEFAULT_NATIVE_WINDOW_SIZE, MIN_NATIVE_WINDOW_SIZE, native_options};
    #[cfg(target_os = "linux")]
    use std::path::Path;

    #[test]
    fn native_window_starts_wide_and_has_a_minimum_width() {
        let viewport = native_options().viewport;

        assert_eq!(
            viewport.inner_size,
            Some(egui::Vec2::from(DEFAULT_NATIVE_WINDOW_SIZE))
        );
        assert_eq!(
            viewport.min_inner_size,
            Some(egui::Vec2::from(MIN_NATIVE_WINDOW_SIZE))
        );
        assert_eq!(
            viewport.icon.as_ref().map(|icon| (icon.width, icon.height)),
            Some((512, 512))
        );
        #[cfg(target_os = "linux")]
        assert_eq!(
            viewport.app_id.as_deref(),
            Some(if cfg!(styrhous_release_build) {
                "styrhous"
            } else {
                "styrhous-dev"
            })
        );
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn linux_desktop_app_id_uses_the_package_entry_for_distributable_builds() {
        assert_eq!(
            linux_desktop_app_id_for(true, false, Some(Path::new("/home/dev/styrhous"))),
            "styrhous"
        );
        assert_eq!(
            linux_desktop_app_id_for(false, true, Some(Path::new("/home/dev/styrhous"))),
            "styrhous"
        );
        assert_eq!(
            linux_desktop_app_id_for(false, false, Some(Path::new("/usr/bin/styrhous"))),
            "styrhous"
        );
        assert_eq!(
            linux_desktop_app_id_for(
                false,
                false,
                Some(Path::new("/nix/store/example-styrhous/bin/styrhous")),
            ),
            "styrhous"
        );
        assert_eq!(
            linux_desktop_app_id_for(
                false,
                false,
                Some(Path::new("/home/dev/styrhous/target/release/styrhous")),
            ),
            "styrhous-dev"
        );
    }
}
